import js from '@eslint/js';

export default [
  {
    ignores: [
      'dist/',
      'drafts/',
      'coverage/',
      'node_modules/',
      'help/',
      'tests/',
      'solid-web-components.bundle.js',
      '**/*~',
      'rollup.config.js',
      'babel.config.cjs',
    ],
  },
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        customElements: 'readonly',
        HTMLElement: 'readonly',
        CSSStyleSheet: 'readonly',
        CustomEvent: 'readonly',
        DOMParser: 'readonly',
        MutationObserver: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        fetch: 'readonly',
        console: 'readonly',
        alert: 'readonly',
        prompt: 'readonly',
        globalThis: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        FormData: 'readonly',
        Response: 'readonly',
        Headers: 'readonly',
        AbortController: 'readonly',
        localStorage: 'readonly',
        requestAnimationFrame: 'readonly',
        queueMicrotask: 'readonly',
        newEngine: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'prefer-const': 'warn',
    },
  },
];
