/**
 * sol-load.js — ci-free component bootstrap.
 *
 * A single CLASSIC script (not a module) that does the one job
 * component-interop otherwise performs for a page: it injects the inline
 * import map that resolves the bare specifiers sol-components use
 * (`rdflib`, `sol-weather`, `sol-components/core/…`, …), then imports the
 * components the tag names. Everything resolves relative to wherever THIS
 * file was loaded from, so the same tag works from node_modules, a pod
 * copy, or a CDN — no local/cdn switch needed.
 *
 * Usage (the tag declares exactly what it loads):
 *
 *   <script src=".../sol-components/web/sol-load.js"
 *           data-components="sol-weather sol-time"></script>
 *
 *   <sol-weather source="weather-settings.ttl#Settings"></sol-weather>
 *
 * Place the tag BEFORE any `<script type="module">` that uses bare
 * specifiers — an import map is only accepted while none of its
 * specifiers have been resolved yet. Bundles: `sol-basic` (everyday UI,
 * incl. from-rdf menus), `sol-pod-bundle` (pod browsing),
 * `sol-form-bundle` (RDF editing).
 *
 * Also exposes `window.solLoad(name)` → the dynamic-import promise, for
 * late/conditional loads, and `window.solLoadReady` — a promise for the
 * components the tag itself named.
 *
 * Pages already running component-interop don't need this file; if both
 * are present, whichever injected an import map first wins (we skip
 * injection when an existing map already resolves `rdflib`).
 *
 * The MAP block below is GENERATED — regenerate with `npm run
 * build:importmaps` after adding a component or vendor dep.
 */
(function () {
  'use strict';

  /* ── generated by tools/build-importmaps.mjs — do not edit by hand ── */
  var MAP = {
      "rdflib": "dist/vendor/rdflib.js",
      "dompurify": "dist/vendor/dompurify.js",
      "ical.js": "dist/vendor/ical.js.js",
      "marked": "dist/vendor/marked.js",
      "@comunica/query-sparql": "dist/vendor/@comunica-query-sparql.js",
      "solid-ui": "dist/vendor/solid-ui.js",
      "solid-logic": "dist/vendor/solid-logic.js",
      "@inrupt/solid-client-authn-browser": "dist/vendor/@inrupt-solid-client-authn-browser.js",
      "n3": "dist/vendor/n3.js",
      "rdf-validate-shacl": "dist/vendor/rdf-validate-shacl.js",
      "menu-from-rdf": "web/menu-from-rdf.js",
      "sol-accordion": "web/sol-accordion.js",
      "sol-app-builder": "web/sol-app-builder.js",
      "sol-basic": "web/sol-basic.js",
      "sol-breadcrumb": "web/sol-breadcrumb.js",
      "sol-button-bar-manager": "web/sol-button-bar-manager.js",
      "sol-button": "web/sol-button.js",
      "sol-calendar": "web/sol-calendar.js",
      "sol-default": "web/sol-default.js",
      "sol-dropdown-button": "web/sol-dropdown-button.js",
      "sol-dropdown": "web/sol-dropdown.js",
      "sol-feed": "web/sol-feed.js",
      "sol-form-bundle": "web/sol-form-bundle.js",
      "sol-form": "web/sol-form.js",
      "sol-gallery": "web/sol-gallery.js",
      "sol-include": "web/sol-include.js",
      "sol-live-edit": "web/sol-live-edit.js",
      "sol-login": "web/sol-login.js",
      "sol-menu-manager": "web/sol-menu-manager.js",
      "sol-menu": "web/sol-menu.js",
      "sol-modal": "web/sol-modal.js",
      "sol-plugin-manager": "web/sol-plugin-manager.js",
      "sol-pod-bundle": "web/sol-pod-bundle.js",
      "sol-pod-extras": "web/sol-pod-extras.js",
      "sol-pod-ops": "web/sol-pod-ops.js",
      "sol-pod": "web/sol-pod.js",
      "sol-query": "web/sol-query.js",
      "sol-rolodex": "web/sol-rolodex.js",
      "sol-search": "web/sol-search.js",
      "sol-settings-nav": "web/sol-settings-nav.js",
      "sol-settings": "web/sol-settings.js",
      "sol-sheet": "web/sol-sheet.js",
      "sol-solidos": "web/sol-solidos.js",
      "sol-tabs": "web/sol-tabs.js",
      "sol-time": "web/sol-time.js",
      "sol-tree-edit": "web/sol-tree-edit.js",
      "sol-wac": "web/sol-wac.js",
      "sol-weather": "web/sol-weather.js",
      "sol-window": "web/sol-window.js",
      "rdf-bundle": "core/rdf-bundle.js",
      "sol-components/core/": "core/",
      "sol-components/sources/": "sources/",
      "sol-components/data/": "data/",
      "sol-components/": "web/"
  };
  /* ── end generated map ── */

  var script = document.currentScript;
  if (!script || !script.src) {
    console.warn('[sol-load] must be loaded via <script src=".../web/sol-load.js">');
    return;
  }
  // …/web/sol-load.js → the sol-components package root.
  var pkgRoot = new URL('..', script.src);

  // Respect a map somebody else already injected (component-interop's,
  // or a hand-written one): duplicate specifier definitions are only
  // cleanly supported in very recent browsers.
  var existing = document.querySelector('script[type="importmap"]');
  var alreadyMapped = false;
  if (existing) {
    try {
      alreadyMapped = !!((JSON.parse(existing.textContent || '{}').imports || {}).rdflib);
    } catch { alreadyMapped = false; }
  }

  if (!alreadyMapped) {
    var imports = {};
    for (var name in MAP) imports[name] = new URL(MAP[name], pkgRoot).href;
    var tag = document.createElement('script');
    tag.type = 'importmap';
    tag.textContent = JSON.stringify({ imports: imports });
    // Nonce-based CSP hosts (e.g. data-kitchen's shell): the injected map is
    // an inline script, so it must carry the nonce our own tag was served
    // with. script.nonce reads the IDL property (the content attribute is
    // hidden post-parse).
    if (script.nonce) tag.nonce = script.nonce;
    script.parentNode.insertBefore(tag, script.nextSibling);
  }

  // Dynamic import() in a classic script resolves through the page's
  // import map, so bare names like 'sol-weather' work here.
  function solLoad(nameOrNames) {
    var names = Array.isArray(nameOrNames) ? nameOrNames : [nameOrNames];
    return Promise.all(names.map(function (n) { return import(n); }));
  }
  window.solLoad = solLoad;

  var wanted = (script.getAttribute('data-components') || '')
    .trim().split(/\s+/).filter(Boolean);
  window.solLoadReady = wanted.length ? solLoad(wanted) : Promise.resolve([]);
  window.solLoadReady.catch(function (err) {
    console.error('[sol-load]', err.message || err);
  });
})();
